import {
  appApi,
  projectApi,
  dialogApi,
  fileApi,
  shellApi,
  clipboardApi,
  windowApi,
  keychainApi,
  diagnosticsApi,
} from './api-core';
import { videoApi, audioApi, sttApi, ttsApi } from './api-media';
import {
  assetsApi,
  grokApi,
  whiskApi,
  imagefxApi,
  chatApi,
  updateApi,
  cloudApi,
  videogenApi,
  collabApi,
  remoteApi,
} from './api-services';

export const api = {
  app: appApi,
  project: projectApi,
  dialog: dialogApi,
  file: fileApi,
  shell: shellApi,
  clipboard: clipboardApi,
  window: windowApi,
  keychain: keychainApi,
  diagnostics: diagnosticsApi,
  video: videoApi,
  audio: audioApi,
  stt: sttApi,
  tts: ttsApi,
  assets: assetsApi,
  grok: grokApi,
  whisk: whiskApi,
  imagefx: imagefxApi,
  chat: chatApi,
  update: updateApi,
  cloud: cloudApi,
  videogen: videogenApi,
  collab: collabApi,
  remote: remoteApi,
};
